### ISSUE TITLE
Self-sizing mode cause scroll jumping

### ISSUE THREAD

**Issue by Elshad** [airbnb/MagazineLayout#9]
**Smartphone:**
 - Device/Simulator: [iPhone6]
 - OS: [iOS 12]
- For self-sizing

Scroll to the last indexPath, rotate device and begin to scroll to top. Scroll will start to jump. 

Reason: 
Imagine we have 1000 cell (1000 item). We are at the last cell. On `invalidateLayout` `UICollectionViewLayout` will calculate only last for example 10-20 cells and other 980 cells height will be same as `estimatedSize.height`. So `contentSize.height` will be less. While we start to scroll top layout will start calculate new visible cells size, `contentSize.height` will grow and scroll starts to jump. -> This problem is encountered on `UICollectionViewFlowLayout` too. I think because calculating 1000 cells size is bad for performance (for 60 fps). And it may be also 10.000 cells. And calculating all cells to define true size of contentSize is bad solution.

Because of you caching cell sizes, jumping is not huge than in `UICollectionViewFlowLayout`

![untitled480trim](https://user-images.githubusercontent.com/2334731/50334862-08bb5600-0523-11e9-815e-ca49ece51684.gif)

Hi-res: [https://youtu.be/LgQehZKhp1Q](url)

**Comment by bryankeller** [comment]
Thanks for filing @Elshad - we've encountered this too at Airbnb, and it seems like it's a `UICollectionViewLayout` bug (we also reproduced it using flow layout).

I wonder if there's a way to work with the `contentOffsetAdjustment` behavior at scroll time to mitigate this. I'll dig a bit more. Worst case scenario, we'll file a radar. Give me a few days to play around with some ideas and I'll post back here with any findings / radars.

**Comment by AamirAnwar** [comment]
@bryankeller Jumps when there aren't those many items too :(
Any workarounds for this?
![screenrecording_12-27-2018 21-58-50](https://user-images.githubusercontent.com/12379620/50487348-f1e59980-0a23-11e9-8c50-4eebcb685f9b.gif)

**Comment by bryankeller** [comment]
@Elshad this is now fixed in 
https://github.com/airbnb/MagazineLayout/releases/tag/v1.0.1. The PR that fixes it is 
https://github.com/airbnb/MagazineLayout/pull/11

**Comment by diegorozen** [comment]
@bryankeller Has the podspec being pushed to Trunk. I still see last version as 1.0

**Comment by haydgately** [comment]
Still seeing this self sizing issue on v1.4.3 if I:  
-Scroll down in the collection view smoothly.
-Push another view controller onto the navigation stack.
-Pop the view controller back to collection view.
-Scroll up and see scrolling is choppy.

I see this was closed but this became a bug about the rotational issue which my issue isn't convinced with. @bryankeller

**Comment by bryankeller** [comment]
@haydgately thanks for the information. It seems odd to me that pushing a completely independent view controller, then popping it, would affect anything in the initial view controller’s collection view. What are you doing in viewWill/DidAppear? Are you reloading data or invalidating the layout?

Do you have a sample project / setup to repro? Any additional information you can provide will be very much appreciated 🙂 And if you think the issue is actually different from this one, feel free to open a new issue.
